# Generated by Django 3.2 on 2021-08-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
