# Generated by Django 3.2 on 2021-08-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=20)),
                ('crop_image', models.ImageField(upload_to='crops/')),
                ('crop_desc', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crop.crop')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CropReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('stars', models.FloatField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
