# Generated by Django 3.2 on 2021-08-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='category',
        ),
        migrations.AlterField(
            model_name='crop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
